### ISSUE TITLE
Pid

### ISSUE THREAD

**Issue by mohamedsiddik-b** [pms67/PID#10]
#include <stdio.h>

#define KP 2.0
#define KI 0.5
#define KD 0.1

float setpoint = 25.0;
float error, last_error, integral, derivative;
float temperature[3], pwm_output[3];

void read_temperature()
{
  // read temperature from sensors and store in temperature array
}

void update_pid()
{
  // calculate error value
  error = setpoint - temperature[0];

  // calculate integral term
  integral += error;

  // calculate derivative term
  derivative = error - last_error;

  // calculate PID output
  pwm_output[0] = KP * error + KI * integral + KD * derivative;

  // limit PWM output to a safe range
  if (pwm_output[0] > 255) pwm_output[0] = 255;
  if (pwm_output[0] < 0) pwm_output[0] = 0;

  // update last_error
  last_error = error;

  // set PWM output to thermoelectric cooler
}

int main()
{
  // initialize integral and last_error
  integral = 0.0;
  last_error = 0.0;

  while (1)
  {
    read_temperature();
    update_pid();
  }

  return 0;
}

**Comment by maksoff** [comment]
@mohamedsiddik-b  You have forgotten to limit the integral part: if you can't achieve the required temperature also with maximum PWM output, it will increase further to the infinity, and at the moment when it finally achieves the temperature, it will take insane time to decrease the integral back to the useful values.
Also the Phil's code have a nice features - low-pass filter for derivative (to mitigate the effect of the high frequency noise), and also derivative on the measurement (temperature - prev_temperature), and not on the error, which prevents the jump of derivative component on setpoint change.
But at first look at my issue  #9  regarding the D-component, original code has a flaw in the implementation.
